from src.services.video import extract_video_metadata, generate_video_thumbnails


def test_video_metadata_extraction_fallback() -> None:
    dummy_video_bytes = b"fake-video-bytes-data"
    duration, width, height = extract_video_metadata(dummy_video_bytes)
    # When ffprobe is not installed or on dummy data, fallback defaults are returned
    assert width is not None
    assert height is not None
    assert width > 0
    assert height > 0


def test_video_thumbnails_generation() -> None:
    dummy_video_bytes = b"fake-video-bytes-data"
    thumbnail_bytes, preview_bytes = generate_video_thumbnails(dummy_video_bytes)

    assert len(thumbnail_bytes) > 0
    assert len(preview_bytes) > 0

    # Ensure generated bytes are valid WebP images
    from PIL import Image
    import io

    thumb_img = Image.open(io.BytesIO(thumbnail_bytes))
    assert thumb_img.format == "WEBP"
    assert thumb_img.width <= 400

    preview_img = Image.open(io.BytesIO(preview_bytes))
    assert preview_img.format == "WEBP"
    assert preview_img.width <= 1600
