"""initial_schema

Revision ID: cbc3142fffb5
Revises: 
Create Date: 2026-06-24 16:22:33.657472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'cbc3142fffb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure auth schema and vector extension are present
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('raw_user_meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('face_search_enabled', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('storage_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_wedding', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('albums',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('dynamic_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'id'),
    postgresql_partition_by='HASH (event_id)'
    )
    op.create_table('exports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('face_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('matched_guest_session_id', sa.Uuid(), nullable=True),
    sa.Column('matched_guest_name', sa.String(), nullable=True),
    sa.Column('cover_thumbnail_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_cache',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('cached_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('guests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('guest_session_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'guest_session_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('upgrade_trigger', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('face_consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('guest_session_id', sa.Uuid(), nullable=False),
    sa.Column('guest_name', sa.String(), nullable=True),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id', 'guest_session_id'], ['guests.event_id', 'guests.guest_session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('guest_session_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('r2_object_key', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('phash', postgresql.BIT(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(uploaded_by IS NOT NULL) OR (guest_session_id IS NOT NULL)'),
    sa.ForeignKeyConstraint(['event_id', 'guest_session_id'], ['guests.event_id', 'guests.guest_session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id', 'id'),
    sa.UniqueConstraint('event_id', 'idempotency_key'),
    postgresql_partition_by='HASH (event_id)'
    )
    op.create_table('album_media',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('album_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id', 'album_id'], ['albums.event_id', 'albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id', 'media_id'], ['media.event_id', 'media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'album_id', 'media_id'),
    postgresql_partition_by='HASH (event_id)'
    )
    op.create_table('face_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('uploader_consent_id', sa.Uuid(), nullable=False),
    sa.Column('purge_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['face_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id', 'media_id'], ['media.event_id', 'media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_consent_id'], ['face_consents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Create the 64 partitions for media, albums, and album_media
    op.execute("""
    DO $$
    DECLARE
        i int;
    BEGIN
        FOR i IN 0..63 LOOP
            EXECUTE format('CREATE TABLE IF NOT EXISTS media_part_%s PARTITION OF media FOR VALUES WITH (MODULUS 64, REMAINDER %s);', i, i);
            EXECUTE format('CREATE TABLE IF NOT EXISTS albums_part_%s PARTITION OF albums FOR VALUES WITH (MODULUS 64, REMAINDER %s);', i, i);
            EXECUTE format('CREATE TABLE IF NOT EXISTS album_media_part_%s PARTITION OF album_media FOR VALUES WITH (MODULUS 64, REMAINDER %s);', i, i);
        END LOOP;
    END;
    $$;
    """)

    # Create public.handle_new_user() function and trigger on auth.users
    op.execute("""
    CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS trigger AS $$
    BEGIN
      INSERT INTO public.users (id, phone, name, role)
      VALUES (
        new.id,
        new.phone,
        new.raw_user_meta_data->>'name',
        COALESCE(new.raw_user_meta_data->>'role', 'host')
      );
      RETURN new;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;
    """)

    op.execute("""
    CREATE OR REPLACE TRIGGER on_auth_user_created
      AFTER INSERT ON auth.users
      FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop trigger and sync function
    op.execute("DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;")
    op.execute("DROP FUNCTION IF EXISTS public.handle_new_user();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_embeddings')
    op.drop_table('album_media')
    op.drop_table('media')
    op.drop_table('face_consents')
    op.drop_table('qr_codes')
    op.drop_table('payments')
    op.drop_table('guests')
    op.drop_table('gallery_cache')
    op.drop_table('face_clusters')
    op.drop_table('exports')
    op.drop_table('albums')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
